BEGIN;

CREATE TABLE IF NOT EXISTS users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(100),
  avatar_url VARCHAR(500),
  background_video_url VARCHAR(500),
  role VARCHAR(50) NOT NULL DEFAULT 'user',
  is_banned INTEGER NOT NULL DEFAULT 0,
  is_premium INTEGER NOT NULL DEFAULT 0,
  premium_expiry TIMESTAMPTZ,
  balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS artists (
  artist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  name VARCHAR(100) NOT NULL,
  bio TEXT,
  image_url VARCHAR(500),
  country VARCHAR(100),
  total_earned NUMERIC(14, 2) NOT NULL DEFAULT 0,
  total_withdrawn NUMERIC(14, 2) NOT NULL DEFAULT 0,
  balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  wallet_balance NUMERIC(14, 2) NOT NULL DEFAULT 0,
  bank_name VARCHAR(100),
  bank_account VARCHAR(100),
  bank_account_name VARCHAR(150),
  membership_price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  membership_duration_days INTEGER NOT NULL DEFAULT 30,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_artists_user_id ON artists(user_id);

CREATE TABLE IF NOT EXISTS genres (
  genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS albums (
  album_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  artist_id INTEGER REFERENCES artists(artist_id) ON DELETE SET NULL,
  release_date TIMESTAMPTZ,
  cover_url VARCHAR(500),
  is_premium INTEGER NOT NULL DEFAULT 0,
  price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_albums_artist_id ON albums(artist_id);

CREATE TABLE IF NOT EXISTS songs (
  song_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  artist_id INTEGER REFERENCES artists(artist_id) ON DELETE SET NULL,
  album_id INTEGER REFERENCES albums(album_id) ON DELETE SET NULL,
  genre_id INTEGER REFERENCES genres(genre_id) ON DELETE SET NULL,
  duration INTEGER,
  file_url VARCHAR(1000) NOT NULL,
  cover_url VARCHAR(1000),
  lyrics TEXT,
  release_date TIMESTAMPTZ,
  listen_count BIGINT NOT NULL DEFAULT 0,
  average_rating NUMERIC(3, 2) NOT NULL DEFAULT 0,
  is_premium INTEGER NOT NULL DEFAULT 0,
  price NUMERIC(14, 2) NOT NULL DEFAULT 0,
  status INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_songs_artist_id ON songs(artist_id);
CREATE INDEX IF NOT EXISTS idx_songs_album_id ON songs(album_id);
CREATE INDEX IF NOT EXISTS idx_songs_genre_id ON songs(genre_id);

CREATE TABLE IF NOT EXISTS playlists (
  playlist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  cover_url VARCHAR(500),
  is_public INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_playlists_user_id ON playlists(user_id);

CREATE TABLE IF NOT EXISTS playlist_songs (
  playlist_id INTEGER NOT NULL REFERENCES playlists(playlist_id) ON DELETE CASCADE,
  song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  "order" INTEGER NOT NULL DEFAULT 0,
  order_index INTEGER,
  PRIMARY KEY (playlist_id, song_id)
);

CREATE INDEX IF NOT EXISTS idx_playlist_songs_song_id ON playlist_songs(song_id);

CREATE TABLE IF NOT EXISTS favorites (
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, song_id)
);

CREATE INDEX IF NOT EXISTS idx_favorites_song_id ON favorites(song_id);

CREATE TABLE IF NOT EXISTS follows (
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  artist_id INTEGER NOT NULL REFERENCES artists(artist_id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, artist_id)
);

CREATE INDEX IF NOT EXISTS idx_follows_artist_id ON follows(artist_id);

CREATE TABLE IF NOT EXISTS comments (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  target_id BIGINT,
  type VARCHAR(100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_song_user ON comments(song_id, user_id);

CREATE TABLE IF NOT EXISTS listening_history (
  history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  artist_id INTEGER REFERENCES artists(artist_id) ON DELETE SET NULL,
  day TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  count INTEGER NOT NULL DEFAULT 1,
  total_duration INTEGER NOT NULL DEFAULT 0,
  completed_count INTEGER NOT NULL DEFAULT 0,
  is_premium_stream INTEGER NOT NULL DEFAULT 0,
  listened_count INTEGER,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, song_id, day)
);

CREATE INDEX IF NOT EXISTS idx_history_user_id ON listening_history(user_id);
CREATE INDEX IF NOT EXISTS idx_history_song_id ON listening_history(song_id);
CREATE INDEX IF NOT EXISTS idx_history_artist_date ON listening_history(artist_id, day);
CREATE INDEX IF NOT EXISTS idx_history_premium_stream ON listening_history(is_premium_stream, day);

ALTER TABLE favorites ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE follows ALTER COLUMN created_at DROP NOT NULL;
ALTER TABLE listening_history ALTER COLUMN updated_at DROP NOT NULL;

CREATE TABLE IF NOT EXISTS notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  type VARCHAR(100),
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  data JSONB,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  read_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at);

CREATE TABLE IF NOT EXISTS purchased_songs (
  purchase_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  price_paid NUMERIC(14, 2) NOT NULL,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  purchased_at TIMESTAMPTZ,
  UNIQUE (user_id, song_id)
);

CREATE INDEX IF NOT EXISTS idx_purchased_songs_song_id ON purchased_songs(song_id);

CREATE TABLE IF NOT EXISTS purchased_albums (
  purchase_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  album_id INTEGER NOT NULL REFERENCES albums(album_id) ON DELETE CASCADE,
  price_paid NUMERIC(14, 2) NOT NULL,
  purchase_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  purchased_at TIMESTAMPTZ,
  UNIQUE (user_id, album_id)
);

CREATE INDEX IF NOT EXISTS idx_purchased_albums_album_id ON purchased_albums(album_id);

CREATE TABLE IF NOT EXISTS transactions (
  transaction_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  amount NUMERIC(14, 2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  description TEXT,
  reference_code VARCHAR(255),
  target_id BIGINT,
  target_type VARCHAR(100),
  admin_note TEXT,
  processed_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transactions_user_type ON transactions(user_id, type);
CREATE INDEX IF NOT EXISTS idx_transactions_status ON transactions(status);
CREATE INDEX IF NOT EXISTS idx_transactions_reference ON transactions(reference_code);
CREATE INDEX IF NOT EXISTS idx_transactions_created ON transactions(created_at);

CREATE TABLE IF NOT EXISTS artist_memberships (
  membership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  artist_id INTEGER NOT NULL REFERENCES artists(artist_id) ON DELETE CASCADE,
  price_paid NUMERIC(14, 2) NOT NULL DEFAULT 0,
  start_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiry_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, artist_id)
);

CREATE INDEX IF NOT EXISTS idx_memberships_user_status ON artist_memberships(user_id, status);
CREATE INDEX IF NOT EXISTS idx_memberships_artist_status ON artist_memberships(artist_id, status);
CREATE INDEX IF NOT EXISTS idx_memberships_expiry ON artist_memberships(expiry_date);

CREATE TABLE IF NOT EXISTS premium_listening_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
  song_id BIGINT REFERENCES songs(song_id) ON DELETE CASCADE,
  artist_id BIGINT REFERENCES artists(artist_id) ON DELETE SET NULL,
  listen_date DATE NOT NULL,
  listen_count INTEGER NOT NULL DEFAULT 0,
  total_duration NUMERIC(14, 2) NOT NULL DEFAULT 0,
  completed_count INTEGER NOT NULL DEFAULT 0,
  UNIQUE (user_id, song_id, listen_date)
);

CREATE TABLE IF NOT EXISTS reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  song_id INTEGER NOT NULL REFERENCES songs(song_id) ON DELETE CASCADE,
  reporter_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  report_type VARCHAR(50) NOT NULL DEFAULT 'other',
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  admin_response TEXT,
  resolved_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  resolved_at TIMESTAMPTZ,
  reason VARCHAR(255),
  target_id BIGINT,
  target_type VARCHAR(100),
  user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_reports_song ON reports(song_id);
CREATE INDEX IF NOT EXISTS idx_reports_reporter ON reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_created ON reports(created_at);

CREATE TABLE IF NOT EXISTS artist_withdrawals (
  withdrawal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  artist_id BIGINT REFERENCES artists(artist_id) ON DELETE CASCADE,
  amount NUMERIC(14, 2) NOT NULL,
  fee NUMERIC(14, 2) NOT NULL DEFAULT 0,
  actual_amount NUMERIC(14, 2),
  bank_name VARCHAR(255),
  bank_account VARCHAR(255),
  bank_account_name VARCHAR(255),
  account_holder_name VARCHAR(255),
  account_number VARCHAR(255),
  artist_note TEXT,
  admin_note TEXT,
  note TEXT,
  status VARCHAR(50) NOT NULL DEFAULT 'pending',
  processed_by INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_artist_status ON artist_withdrawals(artist_id, status);

CREATE TABLE IF NOT EXISTS revenue_sharing (
  sharing_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id INTEGER REFERENCES transactions(transaction_id) ON DELETE SET NULL,
  purchase_id INTEGER REFERENCES purchased_songs(purchase_id) ON DELETE SET NULL,
  album_purchase_id INTEGER REFERENCES purchased_albums(purchase_id) ON DELETE SET NULL,
  artist_id INTEGER REFERENCES artists(artist_id) ON DELETE SET NULL,
  user_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  song_id INTEGER REFERENCES songs(song_id) ON DELETE SET NULL,
  album_id INTEGER REFERENCES albums(album_id) ON DELETE SET NULL,
  share_type VARCHAR(50),
  total_amount NUMERIC(14, 2) NOT NULL DEFAULT 0,
  artist_share NUMERIC(14, 2) NOT NULL DEFAULT 0,
  artist_percentage NUMERIC(5, 2) NOT NULL DEFAULT 70,
  platform_share NUMERIC(14, 2) NOT NULL DEFAULT 0,
  platform_percentage NUMERIC(5, 2) NOT NULL DEFAULT 30,
  calculation_period VARCHAR(20),
  stream_count INTEGER NOT NULL DEFAULT 0,
  listen_duration INTEGER NOT NULL DEFAULT 0,
  is_paid_to_artist INTEGER NOT NULL DEFAULT 0,
  paid_at TIMESTAMPTZ,
  month INTEGER,
  year INTEGER,
  share_amount NUMERIC(14, 2),
  status VARCHAR(50),
  total_premium_streams INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_revenue_artist_period ON revenue_sharing(artist_id, calculation_period);
CREATE INDEX IF NOT EXISTS idx_revenue_artist_type ON revenue_sharing(artist_id, share_type);
CREATE INDEX IF NOT EXISTS idx_revenue_share_type ON revenue_sharing(share_type);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'users', 'artists', 'genres', 'albums', 'songs', 'playlists',
    'comments', 'listening_history', 'transactions', 'artist_memberships',
    'reports', 'artist_withdrawals', 'revenue_sharing'
  ]
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS set_%I_updated_at ON %I', table_name, table_name);
    EXECUTE format(
      'CREATE TRIGGER set_%I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      table_name,
      table_name
    );
  END LOOP;
END;
$$;

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'users', 'artists', 'genres', 'albums', 'songs', 'playlists',
    'playlist_songs', 'favorites', 'follows', 'comments',
    'listening_history', 'notifications', 'purchased_songs',
    'purchased_albums', 'transactions', 'artist_memberships',
    'premium_listening_stats', 'reports', 'artist_withdrawals',
    'revenue_sharing'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
  END LOOP;
END;
$$;

COMMIT;
